--- 
services: 
  haproxy: 
    image: haproxytech/haproxy-debian:2.1.4
    ports:
      - "5555:5555"
      - "8404:8404"
    volumes:
      - ./hack/docker-compose/dataplaneapi-v2.0.1:/etc/haproxy/dataplaneapi-v2.0.1:ro
      - ./hack/docker-compose/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
version: "3.7"
