--- 
services: 
  haproxy: 
    image: haproxytech/haproxy-debian:2.1.4
    ports:
      - "5555:5555"
      - "8404:8404"
    volumes:
      - ./hack/docker-compose/dataplaneapi:/etc/haproxy/dataplaneapi:ro
      - ./hack/docker-compose/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./hack/docker-compose/localhost.pem:/etc/haproxy/localhost.pem:ro
version: "3.7"
